name: CI Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        env:
          SQLALCHEMY_DATABASE_URI: ${{ secrets.SQLALCHEMY_DATABASE_URI }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .

      - name: Run tests
        env:
          SQLALCHEMY_DATABASE_URI: ${{ secrets.SQLALCHEMY_DATABASE_TEST_URI }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
        run: |
          PYTHONPATH=. pytest tests/ -v --disable-warnings
    
  deploy:
    runs-on: ubuntu-latest
    needs: [build, test]  # Зависит от успешного выполнения build и test
    steps:
      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@v1.0.7
        with:
          host: ${{ secrets.SERVER_HOST }}  # IP сервера (185.170.153.5)
          username: ${{ secrets.SERVER_USERNAME }}  # root или ваш пользователь
          key: ${{ secrets.SERVER_SSH_KEY }}  # Приватный SSH-ключ
          script: |
            cd /var/www/backend
            git pull origin master
            source venv/bin/activate
            pip install -r requirements.txt
            sudo systemctl restart backend
            echo "Deployment successful!"